### ISSUE TITLE
Query related to online real-time use

### ISSUE THREAD

**Issue by sophia-wright-blue** [liorsidi/ViolenceDetection_CNNLSTM#1]
Hello,
 
 Thank you for making this code available. I was wondering if you have tried using this model for online real-time detection? What changes would you recommend to use this model for online real-time detection?

Thanks again for releasing the code.

**Comment by liorsidi** [comment]
hey sorry for the late response,
this model was not tested on online real-time detection.

here are some considerations before deploying the model in real-time:
- **framework** - deploy the model as tensorflow to make it faster.
- **pre-processing** - most of the work should be made on the processing of the sequences, you should code a fast sequence generator that takes the last n timesteps and apply the prediction.
- **meta-model** - because the predictions are made threw time, I would build a meta model / accumulative model that predict final prediction given the last k predictions.

s

**Comment by sophia-wright-blue** [comment]
thanks for the detailed reply @liorsidi
