### ISSUE TITLE
Error while running run.py file

### ISSUE THREAD

**Issue by Nakul93** [liorsidi/ViolenceDetection_CNNLSTM#4]
TypeError: 'dict_values' object does not support indexing

**Comment by arianaa30** [comment]
Similarly, after running `run.py` after having the datasets ready, I get this error:

`TypeError: 'dict_values' object is not subscriptable`

**Comment by HempriyaSen** [comment]
TypeError:'dict_values' object is not subscriptable

**Comment by liorsidi** [comment]
@Nakul93 @HempriyaSen  it's because of Python 2.7 and you use python 3. please check this https://stackoverflow.com/questions/17431638/get-typeerror-dict-values-object-does-not-support-indexing-when-using-python

and feel free to change the code locally. 

I set a new task for future versions - support python 3.
